# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb30326462e1eba832c48bafdf9f31b720119f2b5b998a6d9176cb23bf22274da7edea565028e2902554a9a123c389a878a162ce4394b789ba2daa165b0bede5

test:
  secret_key_base: acaccec9b3958e308ce6fbd61519b9d5b533b08443540fe9bc1ecf324ffecb0ea8947339e81d60893582f69f83e3c4f79fe37f4ab746cef6a33edf84b40ca7ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
